import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { formatDate } from './utils';

export async function exportDoctorReport(data: {
  userName: string;
  dateRange: { start: string; end: string };
  cycleSummary: { avgLength: number; avgPeriod: number; variation: number };
  pcodScore: number;
  pcodLevel: string;
  factors: Record<string, number>;
  symptoms: Record<string, number>;
}) {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  
  // Header
  pdf.setFillColor(26, 10, 46);
  pdf.rect(0, 0, pageWidth, 40, 'F');
  pdf.setTextColor(201, 75, 138);
  pdf.setFontSize(22);
  pdf.text('FemTrack AI', 15, 18);
  pdf.setTextColor(179, 157, 219);
  pdf.setFontSize(10);
  pdf.text('Smart Period Tracking & PCOD Risk Report', 15, 28);
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(8);
  pdf.text(`Generated: ${formatDate(new Date())}`, pageWidth - 55, 18);
  
  let y = 55;
  
  // Patient info
  pdf.setTextColor(30, 30, 30);
  pdf.setFontSize(14);
  pdf.text('Patient Report', 15, y);
  y += 10;
  pdf.setFontSize(10);
  pdf.text(`Name: ${data.userName}`, 15, y);
  y += 7;
  pdf.text(`Report Period: ${formatDate(data.dateRange.start)} — ${formatDate(data.dateRange.end)}`, 15, y);
  y += 15;
  
  // Cycle summary
  pdf.setFontSize(12);
  pdf.setTextColor(201, 75, 138);
  pdf.text('Cycle Summary', 15, y);
  y += 8;
  pdf.setFontSize(10);
  pdf.setTextColor(60, 60, 60);
  pdf.text(`Average Cycle Length: ${data.cycleSummary.avgLength} days`, 20, y); y += 6;
  pdf.text(`Average Period Length: ${data.cycleSummary.avgPeriod} days`, 20, y); y += 6;
  pdf.text(`Cycle Variation: ±${data.cycleSummary.variation} days`, 20, y); y += 15;
  
  // PCOD Risk
  pdf.setFontSize(12);
  pdf.setTextColor(201, 75, 138);
  pdf.text('PCOD Risk Assessment', 15, y);
  y += 8;
  pdf.setFontSize(10);
  pdf.setTextColor(60, 60, 60);
  pdf.text(`Risk Score: ${data.pcodScore}/100 (${data.pcodLevel.toUpperCase()})`, 20, y); y += 10;
  
  // Factor breakdown
  pdf.text('Risk Factor Breakdown:', 20, y); y += 7;
  Object.entries(data.factors).forEach(([factor, weight]) => {
    const barWidth = weight * 100;
    pdf.setFillColor(230, 230, 240);
    pdf.rect(25, y - 3, 100, 5, 'F');
    pdf.setFillColor(201, 75, 138);
    pdf.rect(25, y - 3, barWidth, 5, 'F');
    pdf.text(`${factor}: ${(weight * 100).toFixed(1)}%`, 130, y);
    y += 8;
  });
  y += 10;
  
  // Symptoms
  pdf.setFontSize(12);
  pdf.setTextColor(201, 75, 138);
  pdf.text('Symptom Frequency', 15, y);
  y += 8;
  pdf.setFontSize(9);
  pdf.setTextColor(60, 60, 60);
  Object.entries(data.symptoms).forEach(([symptom, count]) => {
    pdf.text(`• ${symptom}: reported ${count} time(s)`, 20, y);
    y += 5;
  });
  
  // Disclaimer
  y = pdf.internal.pageSize.getHeight() - 25;
  pdf.setDrawColor(200, 200, 200);
  pdf.line(15, y, pageWidth - 15, y);
  y += 5;
  pdf.setFontSize(7);
  pdf.setTextColor(150, 150, 150);
  pdf.text('DISCLAIMER: This report is generated by FemTrack AI and is not a medical diagnosis.', 15, y);
  y += 4;
  pdf.text('Please consult a qualified healthcare professional for medical advice, diagnosis, or treatment.', 15, y);
  y += 4;
  pdf.text('© 2026 FemTrack AI. All rights reserved.', 15, y);
  
  pdf.save(`FemTrack_AI_Report_${new Date().toISOString().split('T')[0]}.pdf`);
}

export async function exportChartAsPDF(elementId: string, title: string) {
  const element = document.getElementById(elementId);
  if (!element) return;
  
  const canvas = await html2canvas(element, { backgroundColor: '#1A0A2E', scale: 2 });
  const imgData = canvas.toDataURL('image/png');
  
  const pdf = new jsPDF('l', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const imgWidth = pageWidth - 30;
  const imgHeight = (canvas.height * imgWidth) / canvas.width;
  
  pdf.setFontSize(16);
  pdf.text(title, 15, 15);
  pdf.addImage(imgData, 'PNG', 15, 25, imgWidth, imgHeight);
  pdf.save(`${title.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`);
}
